lint(utility): Fix missing generic case handling in the device loop logic
Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>

diff --git a/kwin-input-devices b/kwin-input-devices
--- a/kwin-input-devices
+++ b/kwin-input-devices
@@ -77,5 +77,9 @@ for device in "${!devices[@]}"; do
         "disable") set_device_status "$sysname" false ;;
         "toggle") toggle_device "$sysname" ;;
         "status") echo "$device: $(get_device_status "$sysname" )" ;;
+        *)
+            printf 'Error: Unsupported operation mode "%s".\n' "$1" 1>&2
+            exit 1
+        ;;
     esac
 done
