feat(utility): Implement get_input_device_sysfs_name utility function
For querying sysfs names from display names.

Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>

diff --git a/kwin-input-devices b/kwin-input-devices
--- a/kwin-input-devices
+++ b/kwin-input-devices
@@ -43,6 +43,63 @@ if test "${#}" != 1; then
     exit 1
 fi
 
+# Query input device's sysfs name from it's display name
+#
+# Environment variables
+# Standard output: Sysfs name of the matched input device
+# Supported return values:
+#
+# * 0: Matching device found
+# * 1: Generic error
+# * 2: No matching device found
+get_input_device_sysfs_name(){
+    local display_name="${1}"; shift
+
+    local sysnames_raw
+    if ! sysnames_raw="$(
+        "${QDBUS:-qdbus}" \
+            org.kde.KWin \
+            /org/kde/KWin/InputDevice \
+            org.freedesktop.DBus.Properties.Get \
+            org.kde.KWin.InputDeviceManager \
+            devicesSysNames
+        )"; then
+        printf 'Error: Unable to query the sysfs names of the kwin input devices.\n' 1>&2
+        return 1
+    fi
+
+    if ! mapfile -t sysnames <<<"${sysnames_raw}"; then
+        printf 'Error: Unable to load the sysnames array.\n' 1>&2
+        return 1
+    fi
+
+    for sysname in "${sysnames[@]}"; do
+        if ! name="$(
+            "${QDBUS:-qdbus}" \
+                org.kde.KWin \
+                "/org/kde/KWin/InputDevice/${sysname}" \
+                org.freedesktop.DBus.Properties.Get \
+                org.kde.KWin.InputDevice \
+                name
+            )"; then
+            printf \
+                'Error: Unable to query the display name of the "%s" input device.\n' \
+                "${sysname}" \
+                1>&2
+            return 1
+        fi
+
+        if test "${display_name}" == "${name}"; then
+            # Matching device found
+            echo "${sysname}"
+            return 0
+        fi
+    done
+
+    # No matching device found
+    return 2
+}
+
 # Check existence of the DEVICES_TO_BE_MANAGED input devices in the running system, and, save their corresponding sysfs device name for future usage
 find_devices() {
     local sysnames_raw
