feat(utility): Implement utility function to disable a single input device
Signed-off-by: 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>

diff --git a/manage-kwin-input-devices b/manage-kwin-input-devices
--- a/manage-kwin-input-devices
+++ b/manage-kwin-input-devices
@@ -310,6 +310,38 @@ enable_device(){
     return 0
 }
 
+# Disable a input device by its sysfs name or its display name
+#
+# Return values:
+#
+# * 0: Operation successful
+# * 2: Generic error
+disable_device(){
+    local device="${1}"; shift
+
+    if ! is_input_device_sysfs_name "${device}"; then
+        if ! sysfs_name="$(get_input_device_sysfs_name "${device}")"; then
+            printf \
+                'Error: Unable to query the sysfs name of the "%s" input device.\n' \
+                "${device}" \
+                1>&2
+            return 2
+        fi
+    else
+        sysfs_name="${device}"
+    fi
+
+    if ! set_device_status "${sysfs_name}" false; then
+        printf \
+            'Error: Unable to disable the "%s" input device.\n' \
+            "${device}" \
+            1>&2
+        return 2
+    fi
+
+    return 0
+}
+
 if ! find_devices; then
     printf 'Error: Unable to find the input devices to manage.\n' 1>&2
     exit 2
